### PR TITLE
Updates

### LINKED ISSUE #46: the media_animation saved to Arweave is not keeping the design
The `media_animation` link like this one below should always have the same design, but now when u refresh the page it changes
https://clo6zxqomato6re3yewy6wd2oubvxfj3uq6bxyb52mhzlgqx.arweave.net/Et3s3g5gJu9Em8Etj1h6dQNblT-u-kPBvgPdMPlZoXg

### LINKED ISSUE #47: Add contract source under packages/contract
Instead of only having the compiled version, it might be good for reference to have the actual source that is deployed.

### LINKED ISSUE #48: Add subgraph under packages/subgraph

### LINKED ISSUE #49: Update to the project structure
When we run `yarn deploy:contract`, the contract should be deployed to a new address with a new version. Then the address should be updated in the config file

> add it to README for clarification

### PR DESCRIPTION
**Pull request by TheLubab**
## In this PR :
- added contract source code under packages
- added subgraph source code under packages
- updated and fixed the sandbox test

- deployed the contract to a new address `basics.testnet` 

- made a centralized config for all packages under `/config.js` and `/metadata.json`
- the version in the main `package.json` represent the deployed version and is updated automatically on each new deploy, same for `contractAddress`

- Updated README

### CODE REVIEW

**Comment by bestatigen** [comment]
It seems like The Graph is syncing currently @achrafismyname

**Comment by TheLubab** [comment]
closes #46

**Review by AshenI99 — COMMENTED** [review]
Looks good for me. 👍 

Just one question though. You have mentioned that the `startBlock` in `subgraph.yml` is also updating when doing a `yarn deploy:contract`. But I cannot find a code piece relating to that.

**Comment by TheLubab** [comment]
hey @AshenI99 we have to update `startBlock` manually, I mentiened that in step 3

**Pull request merged**
